<?php

namespace AppBundle\Repository;

/**
 * TemplateDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
