services:
#    cloud_twilio.example:
#        class: Cloud\TwilioBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    cloud_twilio.twilio_api:
        class: Cloud\TwilioBundle\Service\TwilioWrapper
    cloud_twilio.twilio_capability:
        class: Cloud\TwilioBundle\Service\TwilioCapabilityWrapper
    cloud_twilio.twilio_taskrouter:
        class: Cloud\TwilioBundle\Service\TwilioTaskRouterWrapper
    cloud_twilio.twilio_taskrouter_worker_capability:
        class: Cloud\TwilioBundle\Service\TwilioTaskRouterWorkerCapabilityWrapper